export const ENUM_QUEUES = {
	TEST: 'TEST',
	TEST_ACK: 'TEST_ACK',
	BROAD_CAST: 'BROAD_CAST',
	HEALTH_CHECK: 'HEALTH_CHECK',
	LOGGING_ACTION: 'LOGGING_ACTION',
} as const;

export const ENUM_EVENT_PATTERN = {
	PUSH_MANY_NOTI_ORDER: 'PUSH_MANY_NOTI_ORDER',
	SAVE_ACTION: 'SAVE_ACTION',
} as const;
