export type TelegramGroupName =
	| 'TELEGRAM_GROUP_ID'
	| 'TELEGRAM_GROUP_SUPPERVISOR_ID'
	| 'TELEGRAM_GROUP_ADMIN_ID'
	| 'TELEGRAM_GROUP_CEO_ID'
	| 'TELEGRAM_GROUP_CTO_ID'
	| 'TELEGRAM_GROUP_SALES_ID';
