version: '3.9'
services:
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: elasticsearch:8.8.1
    networks:
      - elasticsearch-network
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin123

  kibana:
    hostname: kibana
    container_name: kibana
    image: kibana:8.8.1
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch-network
    ports:
      - 5601:5601

networks:
  elasticsearch-network: {}
