export const ENUM_QUEUES = {
	TEST: 'TEST',
	TEST_ACK: 'TEST_ACK',
	BROAD_CAST: 'BROAD_CAST',
	HEALTH_CHECK: 'HEALTH_CHECK',
	LOGGING_ACTION: 'LOGGING_ACTION',
	MAIL_SERVICE: 'MAIL_SERVICE',
	DEFAULT: 'DEFAULT',
} as const;

